version: '3'
services:
  quarkushop:
    image: nebrass/quarkushop-monolithic-application:latest
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql-db:5432/demo
    ports:
      - 8080:8080
  postgresql-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=p4SSW0rd
      - POSTGRES_DB=demo
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak